### ISSUE TITLE
The database layout in any form possible (ERD, excel sheet, ...) and an SQL file to update our local databases for development

### ISSUE THREAD

**Issue by ghost** [bmilliron/OpenRPSDev#4]
Could you please provide this spiraltarget? Else people who work on the PHP code are totally blind in terms of what we can do with the database also I can't test since I don't have the database locally

**Comment by irontet** [comment]
I am working on an ERD. I should have it soon.

**Comment by irontet** [comment]
The first ERD has been committed, it is only one table right now, more to come, but this should get you started in terms of user auth.  Please let me know your opinion on adding fields if needed.

**Comment by ghost** [comment]
Ok everything seems to be added so i'm closing this issue
